c_compiler_version:
  - 8.4.0                      # [x86_64]
  - 8.2.0                      # [ppc64le]
cxx_compiler_version:
  - 8.4.0                      # [x86_64]
  - 8.2.0                      # [ppc64le]
build_type:
  - "cpu"
  - "cuda"

xgboost_select_version:
  - "1.0"
  - "2.0"

# tie the variant string to the select version
zip_keys:
  - build_type
  - xgboost_select_version
